name: build, linters, unit tests, ui tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      [master]
  pull_request:
    branches:
      [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with: 
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod project
        run: npm run build:prod 
      - name: linter ts
        run: npm run lint:ts 
      - name: linter scss
        run: npm run lint:scss 
      - name: unit tests
        run: npm run test:unit 
      - name: storybook build
        run: npm run storybook:build 
      - name: ui test
        run: npm run test:ui:ci 
